### ISSUE TITLE
Configuration is different from included plugins

### ISSUE THREAD

**Issue by Dreamystify** [emqx/emqx-plugin-template#24]
Im not sure how you get any configuration data into the plugin as its quite different from any of the other included plugins. How do we access it?

Also there is no priv folder with a schema file in it

Cheers

**Comment by HJianBo** [comment]
Yes, it is different from each other! Because of the `emqx_plugin_template` config format from [Erlang](http://erlang.org/doc/man/config.html), and the others plugin is from [cuttlefish](https://github.com/emqx/cuttlefish)
