### ISSUE TITLE
Issue posting MQTT messages

### ISSUE THREAD

**Issue by jmr11** [emqx/emqx-plugin-template#60]
So I am using an Ubuntu 16.04 on AWS with EMQX 3.1, trying to post MQTT messages to my Dreamfactory mySQL. I am following this tutorial: [Learn, How to save MQTT messages into a MySQL Database](https://www.youtube.com/watch?v=Tp5EFG4W5WU), which runs on EMQ 2.3.5. So far the only thing you had to modify there was this code on:

ubuntu@ip-172-31-19-97:~/emqx-rel/deps/emqx_plugin_template/src$ nano emqx_plugin_template.erl

```
%% Transform message and return
on_message_publish(Message = #message{topic = <<"$SYS/", _/binary>>}, _Env) ->
    {ok, Message};

on_message_publish(Message, _Env) ->

    io:format("publish ~s~n", [emqttd_message:format(Message)]),
    MessageBin = element(12, Message),
    MessageStr = binary_to_list(MessageBin),inets:start(),
    Method = post,URL = "http://127.0.0.1/api/v2/mysql/_table/log",
    Header = [{"X-DreamFactory-Api-Key", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}],
    Type = "application/json",Body = MessageStr,HTTPOptions = [],
    Options = [],
    R = httpc:request(Method, {URL, Header, Type, Body}, HTTPOptions, Options),

    {ok, Message}.
```

I am wondering if there is anything that I need to change in order to make in work in EMQX 3.1.

I have tried changing the emqtt_message:format to emqx_message:format following the full code structure but it didn't work.

**Comment by HJianBo** [comment]
This code can be:
```erlang
on_message_publish(Message = #message{topic = <<"$SYS/", _/binary>>}, _Env) ->
    {ok, Message};

on_message_publish(Message, _Env) ->
    io:format("Publish ~s~n", [emqx_message:format(Message)]),

    MessageBin = element(#message.payload, Message),
    MessageStr = binary_to_list(MessageBin),
    Method = post,
    URL = "http://127.0.0.1/api/v2/mysql/_table/log",
    Header = [{"X-DreamFactory-Api-Key", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}],
    Type = "application/json",
    Body = MessageStr,
    HTTPOptions = [],
    Options = [],

    inets:start(),
    _Res = httpc:request(Method, {URL, Header, Type, Body}, HTTPOptions, Options),
    {ok, Message}.
```

But, It is very very simple code to forward the message to your HTTP server. Maybe you should learn about Erlang program language for developing custom plugins.

Or to trial our [Enterprise edition](https://www.emqx.io/products/enterprise) free. It supports to save data into everywhere.

**Comment by jmr11** [comment]
Thank you very much @HJianBo !
I tried this code and it worked as a charm. 
I also noticed the option to create a plugin but I was a little scared to do it, since I have no background in Erlang. I'll inform myself and try to learn the basics. 
Thank you again.

**Comment by on6133** [comment]
Hi @HJianBo,

I have tried the same code but I still can't post the message to Dreamfactory mySQL.
I used curl command to post the same message to Dreamfactory mySQL and it was workable.
How do I trace the on_message_publish event was triggered?

**Comment by on6133** [comment]
Hi @HJianBo,

I have tried to copy your code again and it is working now.
Thank for your help.
