### ISSUE TITLE
How to call emqx client api in hook?

### ISSUE THREAD

**Issue by juexun** [emqx/emqx-plugin-template#95]
Hi, I'm writing an mysql backend plugin.
I had stored the user subscribed topic list in mysql. I want to resubscribe the topic while reconnecting.
And how can I send offline message back to client while reconnecting.
Can any body have any information about it.
Thanks very much.

**Comment by zmstone** [comment]
Hi @juexun Could you please post the question to emqx discussion ?
https://github.com/emqx/emqx/discussions
